language: python
python:
    - 2.7
    - 3.3
    - 3.5
    - 3.6
    - pypy
notifications:
    email: false

before_install:
    - sudo apt-get update
    - sudo apt-get -y install python-pip
    - sudo pip install --upgrade pip
    - pip install pep8

script:
    - find . -name \*.py -exec pep8 --ignore=E402 {} +
